### ISSUE TITLE
problems with make

### ISSUE THREAD

**Issue by Seikerk** [pret/pokegold-spaceworld#101]
I tried to make gold spaceworld and got this:
rgbasm -h -E -i build/ -DGOLD -o build/slack/slack.o slack/slack.asm
tools/make_shim.py shim.sym > build/shim.asm
/usr/bin/env: ‘python3’: No such file or directory
make: *** [Makefile:90: build/shim.asm] Error 127

Is there anything I can do to solve this?

**Comment by mid-kid** [comment]
Please join the discord server for help using the repository.
