### ISSUE TITLE
Diassemble collision-checking movement routines

### ISSUE THREAD

**Issue by Tauwasser** [pret/pokegold-spaceworld#35]
Working on a pull request for this as well.

**Comment by Pokeglitch** [comment]
I also have a PR on this that I am almost done with...

https://github.com/Pokeglitch/pokegold-spaceworld/tree/movement

**Comment by Tauwasser** [comment]
Luckily, there is only minor overlap:

https://github.com/Tauwasser/pokegold-spaceworld/tree/overworld_functions

I think your work lacks a systematic approach of collision IDs and the differentiation between old and new collision IDs. You renamed some fields, which will be a merge conflict, but other than that, it's okay.

**Comment by Tauwasser** [comment]
Actually, apparently I'm working off of an older tree and what I did is mostly done already. The above points however still hold.

**Comment by Pokeglitch** [comment]
The collision constants are pulled straight from crystal; I didn't do further research to get more accurate descriptions

**Comment by Pokeglitch** [comment]
It looks like we have significant overlap, but between the two of us we are basically done.

I will pull in your changes since you have more details regarding the tile information, and then I'll add in some additional details that I worked on and submit the final pr

**Comment by Pokeglitch** [comment]
Combined Tauwasser's work with mine here: #36

**Comment by ketsuban** [comment]
Triage: This issue can be closed as the relevant work has been committed to the master branch.
