### ISSUE TITLE
I WANT TO HELP YOU IN THE POKÉMON GOLD BETA PROJECT !!!

### ISSUE THREAD

**Issue by DynaIRN** [pret/pokegold-spaceworld#45]
Hello

I'm following up on your work on Pokémon Gold Beta and I want to contribute, I'm not a programmer or anything, but I've been a big fan of the franchise and game competitively since 1999.

I am part of the Smogon community and we are debating on the possibility of creating a battle simulator based on Beta Gold, but for this, we are discussing about the Pojkémon that does not have a defined BST (those that all the stats are defined in 50 or others whose distribution is half strange, like weaker evolutions than initial stages or even the final evolutions of the initial Pokémon that are very weak in comparison to the final evolutions of the commercially initiated initial Pokémon), and we are rightly studying combinations of stats for these Pokémon.

As I was the one who took the initiative there, I want to keep this conversation with you to go through the updates of the Pokémon; changes can occur because it is necessary to find a balance in the game, and at the same time prevent a Pokémon from being very similar to another and also respect the characteristics of each one, I believe that, when your work is complete, you already have how to use these Pokémon that defined stats; I want nothing in return but the satisfaction of helping a very good project like this, of a franchise that made and is part of my life.

**Comment by 2Tie** [comment]
This repository is only for the disassembly of the Space World prototypes, and any alterations done by Team Spaceworld in the future will be done solely to facilitate an English translation; other changes such as your offer to improve Pokémon stats is beyond our scope and intent. That said, afaik we don't have any issues with other persons or groups theorycrafting or trying to 'finish' such things.
