### ISSUE TITLE
Convert the charmap?

### ISSUE THREAD

**Issue by Halfshadow** [pret/pokegold-spaceworld#59]
Do you have an idea to convert the charmap to a G/S/C like? I think is the base to start a translation.

And maybe a way to convert the .PKM structures? Currently the game could be linked only to (J) R/G/B/Y, can't trade with localized 'cause the PKM structure is shorter and then don't matches.

**Comment by 2Tie** [comment]
https://github.com/pret/pokegold-spaceworld/tree/patch yes, the charmap already has english added for the translation. constants that differ per region such as name length should also be changed.

**Comment by Halfshadow** [comment]
Interesting. Thank you. But maybe is better wait when you'll fix also the Joy nurses, the continue function, the out of battle without end the demo and the PCs and maybe the bike, HM moves out of the battle and the bike... Essential stuff. :)

**Comment by Rangi42** [comment]
charmap.asm exists with all the characters.
