### ISSUE TITLE
Simplify the build system

### ISSUE THREAD

**Issue by Rangi42** [pret/pokegold-spaceworld#68]
When pokered, pokegold, and pokecrystal were disassembled, they simply used `INCBIN` for pieces of the baserom that weren't disassembled yet, and had relatively few object files. Currently pokegold-spaceworld has a system that puts everything in a build/ directory, with one or more `SECTION`s per file, and multiple Python tools for generating linkerscript files that somehow involves `; if DEBUG` comments. This seems excessively complicated: I think if the goal is to get the whole ROM disassembled, a simpler system would be better, one that makes it easy to disassemble any arbitrary piece of code or data with as few file edits as possible. (The rgbds overlay feature is an improvement over manual `INCBIN`s, but I don't think that depends on the whole rest of the current build infrastructure.)

**Comment by mid-kid** [comment]
No linkerscript is being generated during build and `; if DEBUG` comments aren't being involved at any point. This build system just has at least one section per file and shim.sym is used to quickly define symbols without adding them to a proper source file.

You don't have to update the linkerscript when adding a new section, as it will be placed at whatever location you specify, and `make linkerscript` can be used to generate a linkerscript from the final .map file, but realistically, it's mostly useful for inspecting the ROM layout easily.

**Comment by Rangi42** [comment]
Cool, in that case the old comments and .py tools will just need deleting.

**Comment by Rangi42** [comment]
The tools and Makefile have been cleaned up; the `; if DEBUG` comments still need removing.
